//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Godel Scheduler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by defaulter-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
// RegisterDefaults 向给定的 runtime.Scheme 注册 Godel 调度器配置对象的默认值设置函数。
// 当 Scheme 需要为 GodelSchedulerConfiguration 对象设置默认值时，会调用注册的函数。
// 该函数将一个特定类型的默认值设置逻辑（SetObjectDefaults_GodelSchedulerConfiguration）
// 与 GodelSchedulerConfiguration 类型关联起来，使得在调用 scheme.Default(obj) 时能够自动应用这些默认值。
// 此函数通常由代码生成工具（如 defaulter-gen）生成，或在 Scheme 初始化阶段被调用。
func RegisterDefaults(scheme *runtime.Scheme) error {

	scheme.AddTypeDefaultingFunc(&GodelSchedulerConfiguration{}, func(obj interface{}) {

		SetObjectDefaults_GodelSchedulerConfiguration(obj.(*GodelSchedulerConfiguration))
	})
	return nil
}

func SetObjectDefaults_GodelSchedulerConfiguration(in *GodelSchedulerConfiguration) {

	SetDefaults_GodelSchedulerConfiguration(in)
}
